### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by leancode** [legat1/SftpPlugin#4]
Just installed this plugin and the install failed. This is on Ubuntu 22.04.
I get this:
Plugin 'SftpPlugin' failed to load.

Traceback (most recent call last):
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/sftp.py", line 11, in <module>
    import paramiko
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: /home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/bcrypt/_bcrypt.abi3.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 125, in load
  File "fman/impl/plugins/plugin.py", line 141, in _load
  File "fman/impl/plugins/plugin.py", line 164, in _load_classes
  File "fman/impl/plugins/plugin.py", line 229, in _load_packages
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/__init__.py", line 1, in <module>
    from .columns import Group, Owner, Permissions
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/columns.py", line 3, in <module>
    from .filesystems import is_sftp, is_ftp
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/filesystems.py", line 20, in <module>
    from .sftp import SftpBackgroundWrapper, SftpConfig, SftpWrapper
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/sftp.py", line 16, in <module>
    import paramiko
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: /home/dom/.config/fman/Plugins/Third-party/SftpPlugin/sftp_plugin/../lib/bcrypt/_bcrypt.abi3.so: invalid ELF header

**Comment by BenjaminKobjolke** [comment]
I got the same problem on windows 11

**Comment by sbob84** [comment]
Same problem on Windows 11. No updates on the issue for almost 2 years, guess the project is dead?

**Comment by TobberH** [comment]
Same problem here on CachyOS
